package com.scypheon.sdk.core.safety

import android.content.Context
import com.scypheon.sdk.core.annotations.SafetyCritical
import com.scypheon.sdk.core.resilience.AegisThermalGovernor
import com.scypheon.sdk.core.resilience.ResilienceCircuitBreaker
import com.scypheon.sdk.core.resilience.ThermalLevel
import com.scypheon.sdk.core.humanitarian.medical.ClinicalValidator
import com.scypheon.sdk.core.agent.xai.MedicalExplainabilityEngine
import com.scypheon.sdk.core.agent.tool.ToolCall
import com.scypheon.sdk.core.agent.tool.ToolResult
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import timber.log.Timber
import javax.inject.Inject
import javax.inject.Singleton
import dagger.hilt.android.qualifiers.ApplicationContext

@SafetyCritical
@Singleton
class SafetyOrchestrator @Inject constructor(
    @ApplicationContext private val context: Context,
    private val safetyPipeline: com.scypheon.sdk.core.safety.helios.SafetyPipeline,
    private val thermalGovernor: AegisThermalGovernor,
    private val circuitBreaker: ResilienceCircuitBreaker,
    private val clinicalValidator: ClinicalValidator,
    private val sessionRiskManager: com.scypheon.sdk.core.safety.helios.SessionRiskManager,
    private val xaiEngine: MedicalExplainabilityEngine
) {
    private val orchestratorScope = CoroutineScope(SupervisorJob() + Dispatchers.Default)

    init {
        Timber.i("🛡️ [ORCHESTRATOR] Initializing Safety Lifecycle & Thermal Governance")
        thermalGovernor.startMonitoring(context, orchestratorScope)
    }

    /**
     * Orchestrates the complete safety and grounding flow for an Edge AI interaction.
     */
    suspend fun secureInteraction(
        sessionId: String,
        userInput: String,
        onSafe: suspend () -> String
    ): String {
        
        // 1. SESSION RISK ESCALATION (First check to save computation)
        if (sessionRiskManager.isLockedDown(sessionId)) {
            Timber.w("🔒 [ORCHESTRATOR] Session locked down due to cumulative risk: $sessionId")
            return "⚠️ [Security Lockdown]: This session has been locked due to repeated safety violations."
        }

        // 2. RESOURCE GOVERNANCE (Pre-Inference)
        if (thermalGovernor.thermalStatus.value == ThermalLevel.CRITICAL) {
            Timber.e("🚨 [ORCHESTRATOR] Thermal Critical! Blocking inference to prevent hardware damage.")
            return "⚠️ [Hardware Protection]: Device temperature is critical. Inference paused."
        }

        // 3. INPUT FILTERING (HELIOS L2/L5B)
        val inputEval = safetyPipeline.evaluateInput(sessionId, userInput)
        
        // Update Risk from Input
        val inputVerdict = mapToVerdict(inputEval.status)
        sessionRiskManager.updateRisk(sessionId, inputVerdict)

        if (inputEval.status == com.scypheon.sdk.core.safety.helios.SafetyPipeline.SecurityStatus.BLOCKED) {
            Timber.w("🚫 [ORCHESTRATOR] Input blocked by HELIOS: ${inputEval.reason}")
            return "⚠️ [Safety Protocol]: ${inputEval.reason ?: "Query blocked for security reasons."}"
        }

        // 4. CIRCUIT BREAKER & EXECUTION
        return try {
            circuitBreaker.execute("inference_engine") {
                // Pure AI Execution
                val rawResponse = onSafe()
                
                // 🛑 CRITICAL FIX: POST-INFERENCE SAFETY CHECK (Vetting the AI's output)
                // Evaluate AI output. Even if input is safe, AI could hallucinate dangerous content.
                val outputEval = safetyPipeline.evaluateOutput(sessionId, rawResponse)
                
                // Update Risk from Output
                val outputVerdict = mapToVerdict(outputEval.status)
                sessionRiskManager.updateRisk(sessionId, outputVerdict)

                if (outputEval.status == com.scypheon.sdk.core.safety.helios.SafetyPipeline.SecurityStatus.BLOCKED) {
                    Timber.e("☣️ [ORCHESTRATOR] Toxic/Unsafe output generated by AI. Blocking to user.")
                    return@execute "⚠️ [Safety Protocol]: The generated response was flagged and blocked by internal safety systems."
                }

                val finalOutputText = if (outputEval.status == com.scypheon.sdk.core.safety.helios.SafetyPipeline.SecurityStatus.FLAGGED) {
                    outputEval.sanitizedPrompt
                } else {
                    rawResponse
                }

                // 5. CLINICAL GROUNDING (Post-processing)
                clinicalValidator.harden(finalOutputText, userInput, sessionId)
            }
        } catch (e: CancellationException) {
            // 🛑 CRITICAL FIX: DO NOT SWALLOW CANCELLATION! Let Coroutine cancel itself.
            Timber.d("🔄 [ORCHESTRATOR] Interaction cancelled by UI lifecycle.")
            throw e 
        } catch (e: Exception) {
            Timber.e(e, "🔥 [ORCHESTRATOR] Core execution failed")
            "⚠️ [System Resilience]: An error occurred while processing. Please consult offline medical materials."
        }
    }

    /**
     * Generates a transparency report for a completed tool execution.
     */
    suspend fun generateTransparencyReport(
        call: ToolCall,
        result: ToolResult
    ): com.scypheon.sdk.core.agent.xai.MedicalExplanationReport {
        return xaiEngine.generateExplanation(call, result)
    }

    // Helper untuk mapping status (agar kode lebih bersih)
    private fun mapToVerdict(status: com.scypheon.sdk.core.safety.helios.SafetyPipeline.SecurityStatus) =
        when (status) {
            com.scypheon.sdk.core.safety.helios.SafetyPipeline.SecurityStatus.BLOCKED -> com.scypheon.sdk.core.safety.helios.SafetyVerdict.BLOCKED
            com.scypheon.sdk.core.safety.helios.SafetyPipeline.SecurityStatus.FLAGGED -> com.scypheon.sdk.core.safety.helios.SafetyVerdict.FLAGGED
            else -> com.scypheon.sdk.core.safety.helios.SafetyVerdict.SAFE
        }
}
