package com.scypheon.sdk.core.safety.helios

import javax.inject.Inject
import javax.inject.Singleton
import timber.log.Timber

/**
 * ToolAuthorizationGateway (HELIOS L4):
 * Validates and authorizes Function Calls generated by the LLM.
 * Implements Risk-Tiered Consent for critical actions.
 */
@Singleton
class ToolAuthorizationGateway @Inject constructor() {

    enum class RiskTier { LOW, MEDIUM, CRITICAL }
    
    data class AuthorizationResult(
        val isAuthorized: Boolean,
        val needsUserConsent: Boolean,
        val reason: String? = null
    )

    /**
     * Authorizes a tool call based on its defined risk level.
     */
    fun authorize(toolName: String, parameters: Map<String, Any?>): AuthorizationResult {
        val tier = determineRiskTier(toolName)
        
        Timber.i("🛠️ [HELIOS L4] Authorizing tool: $toolName (Tier: $tier)")

        return when (tier) {
            RiskTier.LOW -> AuthorizationResult(true, false)
            RiskTier.MEDIUM -> AuthorizationResult(true, true, "Standard confirmation required.")
            RiskTier.CRITICAL -> AuthorizationResult(false, true, "Critical action requires biometric authentication.")
        }
    }

    private fun determineRiskTier(toolName: String): RiskTier {
        return when (toolName.lowercase()) {
            "discover_openfda" -> RiskTier.MEDIUM
            "get_current_location", "list_contacts" -> RiskTier.MEDIUM
            "send_emergency_broadcast", "wipe_sensitive_data" -> RiskTier.CRITICAL
            else -> RiskTier.LOW
        }
    }
}
