package com.scypheon.sdk.core.safety.helios

import javax.inject.Inject
import javax.inject.Singleton
import timber.log.Timber

/**
 * ToolAuthorizationGateway (HELIOS L4):
 * Validates and authorizes Function Calls generated by the LLM.
 * Implements Risk-Tiered Consent for critical actions and delegates
 * dynamic semantic checks to the YoloSecurityClassifier.
 */
@Singleton
class ToolAuthorizationGateway @Inject constructor(
    private val yoloClassifier: YoloSecurityClassifier
) {

    enum class RiskTier { LOW, MEDIUM, CRITICAL }
    
    data class AuthorizationResult(
        val isAuthorized: Boolean,
        val needsUserConsent: Boolean,
        val reason: String? = null
    )

    /**
     * Authorizes a tool call based on its defined risk level and semantic safety.
     */
    suspend fun authorize(toolName: String, parameters: Map<String, Any?>, contextHistory: String = ""): AuthorizationResult {
        val tier = determineRiskTier(toolName)
        
        Timber.i("🛠️ [HELIOS L4] Authorizing tool: $toolName (Tier: $tier)")

        // Static Tier Overrides
        if (tier == RiskTier.CRITICAL) {
            return AuthorizationResult(false, true, "Critical action requires biometric authentication.")
        }
        
        // Dynamic Semantic Classification via YOLO 2-Stage Classifier
        // We run the classifier for all non-low tier tools, or tools that need context checking
        if (tier != RiskTier.LOW) {
            val classifierResult = yoloClassifier.classifyToolAction(toolName, parameters, contextHistory)
            
            if (classifierResult.shouldBlock) {
                Timber.w("🛡️ [HELIOS L4] Action BLOCKED by YOLO Classifier (Stage ${classifierResult.stage}): ${classifierResult.reason}")
                return AuthorizationResult(
                    isAuthorized = false, 
                    needsUserConsent = true, 
                    reason = "YOLO Classifier Block: ${classifierResult.reason}"
                )
            }
        }

        return when (tier) {
            RiskTier.LOW -> AuthorizationResult(true, false)
            RiskTier.MEDIUM -> AuthorizationResult(true, true, "Standard confirmation required.")
            else -> AuthorizationResult(false, true, "Unknown risk tier blocked for safety.")
        }
    }

    private fun determineRiskTier(toolName: String): RiskTier {
        return when (toolName.lowercase()) {
            "discover_openfda" -> RiskTier.MEDIUM
            "get_current_location", "list_contacts" -> RiskTier.MEDIUM
            "send_emergency_broadcast", "wipe_sensitive_data", "calculate_clinical_dosage" -> RiskTier.CRITICAL
            else -> RiskTier.LOW
        }
    }
}
