package com.scypheon.sdk.core.utils

/**
 * GENERATED BY GRADLE SolarisProvenanceTask. DO NOT EDIT MANUALLY.
 * Hardcoded SHA-256 Provenance for Deterministic Asset Hardening.
 */
object ModelHashes {
    
    
    // Fallback / Placeholder for Build Stability if assets missing during CI
    const val GEMMA_2B_Q6_PLACEHOLDER = "PLACEHOLDER_HASH"
}